version: '3'
name: wg-discord
services:
  wg-discord:
    build:
      context: ./
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - wg-discord-volume:/etc/wireguard

volumes:
  wg-discord-volume:
